FROM node:12

# make target directory for assigning permissions
RUN mkdir -p /usr/src/app/node_modules
RUN chown -R node:node /usr/src/app

# use target directory
WORKDIR /usr/src/app

# set user
USER node

# copy package*.json separately to prevent re-running npm install with every code change
COPY --chown=node:node package.json .
COPY --chown=node:node yarn.lock .
RUN yarn

# copy the project code (e.g. consider: --only=production)
COPY --chown=node:node . .

ENV NUXT_HOST 0.0.0.0
ENV NUXT_PORT 3333
