version: "3.8"

services:
  app:
    container_name: eventbostest
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # 'hack' prevents node_modules/ in the container from being overridden
    working_dir: /usr/src/app
    command: yarn test:e2e
    environment:
      PORT: 3500
      NODE_ENV: test
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: eventbostest
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_CONNECTION: postgres
      JWT_PRIVATE_KEY: key4%#83
      JWT_ACCESS_TOKEN_EXPIRATION: 1h
    networks:
      - testnet
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgis/postgis:13-master
    networks:
      - testnet
    environment:
      POSTGRES_DB: eventbostest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  testnet:

volumes:
  pgdata:
  logs:
