export const USER_REPOSITORY = 'USER_REPOSITORY';
export const EVENT_REPOSITORY = 'EVENT_REPOSITORY';
export const CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY';
export const RESERVATION_REPOSITORY = 'RESERVATION_REPOSITORY';
export const secretOrKey = process.env.JWT_PRIVATE_KEY;
